### ISSUE TITLE
Import Constructor for Table has wrong ImportExportKind

### ISSUE THREAD

**Issue by mayerraphael** [migueldeicaza/WasmerSharp#17]
Constructing an import for a table seems to create a function import.

![image](https://user-images.githubusercontent.com/25869389/111149712-8305a400-858d-11eb-9e28-d23df7708bde.png)

An ImportExportKind.Table seems to exist:
![image](https://user-images.githubusercontent.com/25869389/111149961-ceb84d80-858d-11eb-819f-969985223c16.png)

**Comment by migueldeicaza** [comment]
Thank you for this bug report, this has been fixed.
