### ISSUE TITLE
Erro run DesktopSample

### ISSUE THREAD

**Issue by alexsandro-xpt** [migueldeicaza/WasmerSharp#3]
I'm test this project but I can't run it, I got 
```
System.ArgumentException: 'The specified Type must not be a generic type definition.
Parameter name: delegate'
```
at https://github.com/migueldeicaza/WasmerSharp/blob/5b8edae710d312c964db09c7ac50e6215f5dd4b1/WasmerSharp/Wasmer.cs#L1024-L1026

![image](https://user-images.githubusercontent.com/845657/62226878-458cdc80-b391-11e9-81e2-3224b8d47eb9.png)

There are some things I should do?

**Comment by migueldeicaza** [comment]
I fixed that, it really is a shame that .NET does not support this (but Mono does).
