### ISSUE TITLE
Remove wasmer-runtime native dependency.

### ISSUE THREAD

**Issue by xodo-shared** [migueldeicaza/WasmerSharp#5]
WasmerSharp has native dependencies unmanaged /native wasmer-runtime. 
This prevents use in lambda/cloud functions or deployment with high security requirements.
To address this WASM run-time must be ported/compiled to MSIL.

**Comment by migueldeicaza** [comment]
This is not realistic.   But feel free to fork and prove me wrong :-)

**Comment by RyanLamansky** [comment]
WebAssembly for .NET, https://github.com/RyanLamansky/dotnet-webassembly, is pure .NET and would work in those environments.

I know this issue is long closed, I'm just leaving this here in case someone comes in from a search engine.
